Update to REST endpoints
wkspower/wks-platform pull request #144
Opened 2023-09-06 04:54 UTC by sindhunaydu

### What's in here

Addresses https://github.com/wkspower/wks-platform/issues/116

Updated REST endpoints with the correct annotations and their corresponding tests.

2023-09-06 11:09 UTC, francav submitted a review, later dismissed

2023-09-07 10:42 UTC, francav requested changes

2023-09-07 10:42 UTC, francav commented on apps/react/case-portal/src/services/ProcessDefService.js
Why are we deleting this function?

2023-09-10 18:57 UTC, sindhunaydu commented on apps/react/case-portal/src/services/ProcessDefService.js
@francav since the GET function in [ProcessDefinitionController](https://github.com/wkspower/wks-platform/pull/144/files#diff-5a31b54f074f977eb50589702b0ee3bafcaf5f886fddaec7838c85c55334e373L53) was deleted I deleted this function. But this is not the same GET function. so putting it back.

2023-09-11 09:17 UTC, francav approved these changes

2023-09-11 09:17 UTC, merged

2023-09-11 09:58 UTC, francav commented
Thanks for the great work @sindhunaydu Let me know if looking for other issues =)

2023-09-11 17:21 UTC, sindhunaydu commented
> Thanks for the great work @sindhunaydu Let me know if looking for other issues =)

This was fun! thanks for your help @francav. Will keep an eye out for more issues that I can work on. 👍🏽